// --- static JSON generated by GitHub Actions ---
const SERIES_URL = './data/series.json';
const data = await safeFetchJson(SERIES_URL);
renderSeries(data);

// const CURRENT_MATCHES_URL = './data/current_matches.json'; // if you use it later

const container = document.getElementById('series-container');

// ---- helpers ----
const MONTHS = { jan:0,feb:1,mar:2,apr:3,may:4,jun:5,jul:6,aug:7,sep:8,oct:9,nov:10,dec:11 };

const diagEl = document.getElementById('diag');


function parseSeriesDate(dateStr, fallbackYear) {
  const iso = /^(\d{4})-(\d{2})-(\d{2})$/.exec((dateStr || '').trim());
  if (iso) {
    const [_, y, m, d] = iso;
    return new Date(Date.UTC(+y, +m - 1, +d));
  }
  const md = /^([A-Za-z]{3})\s+(\d{1,2})$/.exec((dateStr || '').trim());
  if (md && fallbackYear) {
    const month = MONTHS[md[1].toLowerCase()];
    const day = +md[2];
    return new Date(Date.UTC(fallbackYear, month, day));
  }
  return new Date(NaN);
}

function todayUTCDateOnly() {
  const now = new Date();
  return new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
}

async function safeFetchJson(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`HTTP ${r.status}`);
  return r.json();
}

function renderSeries(payload) {
  if (!container) return;
  container.innerHTML = '';

  if (!payload || !Array.isArray(payload.data)) {
    container.innerHTML = `<pre style="color:#c33;background:#222;padding:8px;border-radius:6px">
    Unexpected JSON shape:
    ${JSON.stringify(payload, null, 2)}</pre>`;
    return;
  }
// After validating payload.data
  diagEl && (diagEl.textContent = `Series returned: ${payload.data.length}`);


  const latestSeries = payload.data.slice(0, 10);
  const todayUTC = todayUTCDateOnly();

  latestSeries.forEach(series => {
    const start = parseSeriesDate(series.startDate, null);
    const fy = !isNaN(start) ? start.getUTCFullYear() : todayUTC.getUTCFullYear();
    let end = parseSeriesDate(series.endDate, fy);
    if (!isNaN(start) && !isNaN(end) && end < start) {
      end = new Date(Date.UTC(end.getUTCFullYear() + 1, end.getUTCMonth(), end.getUTCDate()));
    }
    const isActive = !isNaN(start) && !isNaN(end) && todayUTC >= start && todayUTC <= end;

    // Build the tile (INSIDE the forEach)
    const tile = document.createElement('div');
    tile.style.border = '1px solid #2a2f3b';
    tile.style.padding = '12px 14px';
    tile.style.margin = '10px 0';
    tile.style.borderRadius = '12px';

    // Use dark background for inactive; soft green for active
    tile.style.backgroundColor = isActive ? '#113b1b' : '#141922';
    // Force readable text on both backgrounds
    tile.style.color = '#e6e8ee';

    tile.innerHTML = `
      <h3 style="margin: 0 0 6px 0; font-weight:600">${series.name}</h3>
      <p style="margin: 0; color: #9aa4b2">Start: ${series.startDate ?? '—'} | End: ${series.endDate ?? '—'}</p>
      <p style="margin: 6px 0 0 0; color: #9aa4b2">Matches: ${series.matches ?? '—'}</p>
      ${isActive ? '<span style="display:inline-block;margin-top:8px;padding:2px 8px;border-radius:999px;border:1px solid #2dbf5c;color:#b8f3cd;font-weight:600;font-size:.8rem">ACTIVE NOW</span>' : ''}
    `;

    container.appendChild(tile);
  });

  // ... after the forEach (when done)
  diagEl && (diagEl.textContent = `Series shown: ${Math.min(payload.data.length, 10)}`);

}



// ---- boot ----
// Make sure your <script> tag is at the end of <body> or has defer, so #series-container exists.
(async function init() {
  try {
    const data = await safeFetchJson(SERIES_URL);
    renderSeries(data);
  } catch (e) {
    console.error('Failed to load series.json:', e);
    if (container) {
      container.innerHTML = '<p style="color:#c33">Could not load data. Try again later.</p>';
    }
  }
})();
