name: Fetch cricket series JSON

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm i node-fetch@3

      - name: Fetch series and write JSON
        env:
          CRICAPI_KEY: ${{ secrets.CRICAPI_KEY }}
        run: node fetch_cricket.js

      - name: Commit changes (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: refresh series.json from API"
          branch: ${{ github.ref_name }}
